# Generated by Django 4.2.6 on 2023-11-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
