# Generated by Django 4.2.6 on 2023-11-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psf', '0002_event_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelterchild',
            old_name='child_discription',
            new_name='child_description',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(upload_to='event/2023-11-03/'),
        ),
        migrations.AlterField(
            model_name='shelterchild',
            name='child_image',
            field=models.ImageField(upload_to='shelter-child/2023-11-03/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='tm_image',
            field=models.ImageField(upload_to='team-member/2023-11-03/'),
        ),
    ]
