# Generated by Django 4.2.6 on 2023-11-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psf', '0005_document_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_status',
            field=models.BooleanField(default=True),
        ),
    ]
