# Generated by Django 4.2.7 on 2023-11-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psf', '0010_alter_document_document_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('contact_message', models.TextField()),
                ('uc_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document_video',
            field=models.FileField(upload_to='document/2023-11-23/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(upload_to='event/2023-11-23/'),
        ),
        migrations.AlterField(
            model_name='shelterchild',
            name='child_image',
            field=models.ImageField(upload_to='shelter-child/2023-11-23/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(upload_to='slider/2023-11-23/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='tm_image',
            field=models.ImageField(upload_to='team-member/2023-11-23/'),
        ),
    ]
