# Generated by Django 4.2.7 on 2023-11-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psf', '0011_usercontact_alter_document_document_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usercontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
