# Generated by Django 4.2.7 on 2023-12-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psf', '0016_alter_document_document_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_video',
            field=models.FileField(upload_to='document/2023-12-28/'),
        ),
        migrations.AlterField(
            model_name='shelterchild',
            name='child_image',
            field=models.ImageField(upload_to='shelter-child/2023-12-28/'),
        ),
    ]
