# Generated by Django 4.2.7 on 2024-01-02 10:13

from django.db import migrations, models
import psf.models


class Migration(migrations.Migration):

    dependencies = [
        ('psf', '0019_alter_document_document_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=250)),
                ('video_description', models.TextField()),
                ('video_link', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document_video',
            field=models.FileField(blank=True, null=True, upload_to=psf.models.document_path),
        ),
    ]
