# Generated by Django 4.2.7 on 2023-11-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_alter_sponsorprofile_sponsor_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsorprofile',
            old_name='sponsor_full_name',
            new_name='sponsor_first_name',
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='sponsor_child_request',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='sponsor_last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
