# Generated by Django 4.2.7 on 2023-12-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_rename_sponsor_full_name_sponsorprofile_sponsor_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spcall_email', models.EmailField(max_length=254)),
                ('spcall_first_name', models.CharField(max_length=150)),
                ('spcall_last_name', models.CharField(max_length=150)),
                ('spcall_phone_number', models.CharField(max_length=11)),
                ('spcall_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
