# Generated by Django 4.2.7 on 2023-12-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0004_sponsorcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorcall',
            name='spcall_number_child',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
