# Generated by Django 4.2.7 on 2024-01-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0006_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='donate_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
