# Generated by Django 4.2.7 on 2024-01-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0008_donate_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='donate_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
