# Generated by Django 4.2.6 on 2023-11-04 12:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('staff', '0002_delete_staff_officestaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficeStaff',
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.customuser',),
            managers=[
                ('staff', django.db.models.manager.Manager()),
            ],
        ),
    ]
