# Generated by Django 4.2.7 on 2023-11-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staffprofile_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_image',
            field=models.ImageField(blank=True, null=True, upload_to='staff/2023-11-18/'),
        ),
    ]
