# Generated by Django 4.2.7 on 2023-12-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_staffprofile_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_image',
            field=models.ImageField(blank=True, null=True, upload_to='staff/2023-12-08/'),
        ),
    ]
