# Generated by Django 4.2.7 on 2023-11-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DONAR', 'Donar'), ('STAFF', 'Staff'), ('CHILD', 'Child')], max_length=30),
        ),
    ]
