# Generated by Django 4.2.7 on 2023-11-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DONAR', 'Donar'), ('SPONSOR', 'Sponsor'), ('STAFF', 'Staff'), ('CHILD', 'Child')], max_length=30),
        ),
    ]
