# Generated by Django 4.2.7 on 2023-11-09 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_customuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.customuser',),
            managers=[
                ('child', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_full_name', models.CharField(max_length=250)),
                ('child_phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('child_image', models.ImageField(blank=True, null=True, upload_to='children/2023-11-10/')),
                ('child_father_name', models.CharField(max_length=250)),
                ('child_mother_name', models.CharField(max_length=250)),
                ('child_date_of_birth', models.DateField()),
                ('child_birth_certificate_number', models.CharField(max_length=250, unique=True)),
                ('child_blood', models.CharField(max_length=250)),
                ('child_weight', models.FloatField()),
                ('child_height', models.FloatField()),
                ('child_present_address', models.TextField()),
                ('child_parmanent_address', models.TextField()),
                ('child_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
