# Generated by Django 4.2.7 on 2023-11-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='child_image',
            field=models.ImageField(blank=True, null=True, upload_to='children/2023-11-14/'),
        ),
    ]
