# Generated by Django 4.2.7 on 2023-11-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_alter_childprofile_child_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='child_full_name',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='child_first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='child_last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='child_image',
            field=models.ImageField(blank=True, null=True, upload_to='children/2023-11-18/'),
        ),
    ]
