# Generated by Django 4.2.7 on 2023-11-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_remove_childprofile_child_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='child_blood',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='child_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='child_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='child_father_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='child_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='child_image',
            field=models.ImageField(blank=True, null=True, upload_to='children/2023-11-19/'),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='child_mother_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='child_parmanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='child_present_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='child_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
