# Generated by Django 4.2.7 on 2023-11-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_alter_childprofile_child_blood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='child_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='child.child'),
        ),
    ]
