# Generated by Django 4.2.7 on 2023-11-18 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('child', '0005_alter_childprofile_child_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='child_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
