# Generated by Django 4.2.7 on 2023-11-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0006_alter_childprofile_child_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='child_birth_certificate_number',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
