# Generated by Django 4.2.7 on 2023-11-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0007_alter_childprofile_child_birth_certificate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='child_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
