# Generated by Django 4.2.7 on 2023-11-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0008_alter_childprofile_child_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='child_image',
            field=models.ImageField(blank=True, null=True, upload_to='children/2023-11-23/'),
        ),
    ]
