# Generated by Django 4.2.7 on 2023-12-27 16:55

import child.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('child', '0012_alter_childprofile_child_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='child_image',
            field=models.ImageField(blank=True, null=True, upload_to=child.models.child_image_path),
        ),
        migrations.CreateModel(
            name='ChildProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_year', models.DateField()),
                ('progress_title', models.CharField(max_length=250)),
                ('progress_description', models.TextField(blank=True, null=True)),
                ('progress_image', models.ImageField(upload_to=child.models.progress_image_path)),
                ('progress_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('child_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
