# Generated by Django 4.2.7 on 2023-12-29 11:03

import child.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0014_alter_childprogress_progress_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='child_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=child.models.child_image_path),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='child_hobbie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='child_join',
            field=models.DateField(blank=True, null=True),
        ),
    ]
