# Generated by Django 4.2.7 on 2024-01-01 17:41

import child.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0015_childprofile_child_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='child_study',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='child_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=child.models.child_cover_image_path),
        ),
    ]
